### PR TITLE
some "patches"

### PR DESCRIPTION
**Pull request by nkk71**
- Add by-name support (M7): allows to populate by-name symlinks using emmc
- Add bootdevice: patches current mrom-devices.c to add /dev/block/bootdevice/
- MR_DEVICE_SPECIFIC_VERSION in BoardConfig is easier to handle (imho) when building for various devices

All the above need the corresponding flags set in BoardConfig, otherwise they will have no effect, and therefore also little impact on the current code.

### CODE REVIEW

**Comment by Tasssadar** [comment]
Hmm, I don't really like this. Do we need it at all? Are the 'bootdevice' paths used in fstab or something?

Also, angler uses [just one symlink](https://android.googlesource.com/device/huawei/angler/+/master/init.angler.rc#44) to create this, maybe we can do the same somewhere in device hooks or define the path in BoardConfig and then create the symlink only if neccessary?

**Comment by CaptainThrowback** [comment]
The bootdevice paths are used in fstab, yes. Adding the symlink like angler has doesn't work on HTC devices. Trust me, I've tried. There is existing support in system/core for bootdevice symlinks, based on patches from caf and a corresponding BoardConfig flag that handles them. Using that code might be a better way to go in this instance. See here: https://github.com/omnirom/android_system_core/commit/7f6937e1e5bd6ac89ea6c0b18490e88e29738b9a https://github.com/omnirom/android_system_core/commit/54e12a8e752cdbdb4190795f2f83530a00c8ac84
https://github.com/omnirom/android_system_core/commit/d450742c9f9f2dc1c331e57f5b343972cadecd54

And the BoardConfig flag here: https://github.com/TeamWin/android_device_htc_hima/blob/android-5.1/BoardConfig.mk#L89

**Comment by Tasssadar** [comment]
Do you know exactly why did it not work? To me, the contents of both folders under /dev/block/ look the same...?

**Comment by CaptainThrowback** [comment]
I don't, unfortunately. But I tried it a bunch of different ways, and only with the code I linked and BoardConfig flag would it work. Maybe it's related to the kernel, but I'm really not sure.

**Comment by nkk71** [comment]
yes, /dev/block/bootdevice is used in fstab, so it would need to be there, before trampoline attempts to mount data

**Comment by nkk71** [comment]
deprecated.

**Pull request closed without merging**
